### ISSUE TITLE
Plotting of self-loop is not supported 

### ISSUE THREAD

**Issue by HamedMP** [paulbrodersen/netgraph#11]
Fixing the previous bug about `true_division` in numpy here #10, it would be nice to support self-loops. 

```shell
/anaconda3/lib/python3.6/site-packages/netgraph/_main.py:848: UserWarning: Plotting of self-loops not supported. Ignoring edge (X, Y).
  warnings.warn("Plotting of self-loops not supported. Ignoring edge ({}, {}).".format(source, target))

```

**Comment by iD4rksid3** [comment]
same

**Comment by paulbrodersen** [comment]
I know it has been a while but self-loops are as of 4.0.0 fully supported for static and interactive graphs with straight and curved edges (albeit not with bundled edges).
