### ISSUE TITLE
interactive graph not working when changing shape

### ISSUE THREAD

**Issue by godinezmaciask** [paulbrodersen/netgraph#12]
I created a graph with networkx 2.1. Then, I used netgraph 3.1.2 to display my graph in Jupiter Notebook (using Python 3.5) as an Interactive graph, when I want to use a different shape for different nodes, the nodes aren't moving unless they are circles.

I tried both changing all nodes to different shapes, and having some circles and some different shapes. The selection (multiple nodes) functionality is no longer functional when I change shapes too. (I'm guessing it has something to do with the node creation that is being somehow altered)

**Comment by paulbrodersen** [comment]
Should be fixed now by 4ba3d23 but I haven't tested it yet as well as I should (and should have before). Let me know if it works (or doesn't work). New version is 3.1.4.
