### ISSUE TITLE
Interactive Graph: starting node positions

### ISSUE THREAD

**Issue by HolgerGH** [paulbrodersen/netgraph#15]
Is it somehow possible to start the interactive Graph with previously serialized node_positions?

I have successfuly used the interactive graph to define my layout but now I would like to edit it when a new node is added. 

I tried overwritting it directly but that only breaks everything.
```
interGraph = netgraph.InteractiveGraph(graph)
interGraph.node_positions = new_positions
```

I'm trying to use this to accomplish a Process Status Monitoring:

![image](https://user-images.githubusercontent.com/45972767/63031081-b5cc4f80-beb3-11e9-8ceb-1e47873a9d76.png)

**Comment by paulbrodersen** [comment]
Not 100% sure what you are trying to achieve. 

You can initialize a new graph with precomputed node_positions using:
```python
old_graph = [(0, 1), (1, 2), (2, 0)]
first_instance = netgraph.InteractiveGraph(old_graph)
# move stuff around 
first_positions = first_instance.node_positions
new_graph = old_graph + [(2, 3)]
second_instance = netgraph.InteractiveGraph(new_graph, node_positions=first_positions)
```
This should create a new instance in which all nodes have the same position as in the old instance apart from node `3`, which is new. The new node should be in a decent place, as its position is based on the layout of all others.

**Comment by paulbrodersen** [comment]
FYI, there is a class called `InteractiveGrid` which inherits from `InteractiveGraph` but forces node positions to be on a grid (pressing 'g' toggles the grid). Makes it easier to align stuff. You will need to increase the `node_size` as the default will be too small. 
For example:
```
graph = [(0, 1), (1, 2), (2, 3), (3, 0)]
instance = netgraph.InteractiveGrid(graph, node_size=20)
```

**Comment by HolgerGH** [comment]
Just what I needed! Both actually! Seems like I tried the keyword arguments but somehow made a mistake the first time. Then I assumed it doesn't work that way.

I'm thrilled :)

![image](https://user-images.githubusercontent.com/45972767/63078576-3b93dd80-bf3c-11e9-9a52-41ee98bcb68e.png)

**Comment by paulbrodersen** [comment]
No worries, the documentation is still lacking a bit. Let me know if you run into any other issues. Always happy to get feedback.

**Comment by HolgerGH** [comment]
Actually :) . 
Warning: I'm probably not using the right terms as I am just starting with matplotlib.

For my use case it would be great to have a bigger editing canvas when using the InteractiveGrid. I again tried to manipulate the axes limits after calling InteractiveGrid but that only broke everything again:

graph=nx.from_pandas_edgelist(df_hierarchie, 'from', 'to',create_using=nx.DiGraph()) 
labels = {node:node for node in list(graph.nodes)}
fig = plt.figure(figsize=(13,7))
ax  = plt.gca()

# Create an interactive plot.
# NOTE: you must retain a reference to the object instance!
# Otherwise the whole thing will be garbage collected after the initial draw
# and you won't be able to move the plot elements around.
interGraph = netgraph.InteractiveGrid(graph,ax=ax,node_positions=first_positions,node_labels=labels,node_size=15, edge_width=5)

#Attempts to enlarge the editing area:
#ax.set_limx(auto=True)
#ax.set_limx(-200,200)
#ax.set_limy(-200,200)

**Comment by paulbrodersen** [comment]
`ax.set_limx` doesn't exist in matplotlib. I think you mean `ax.set_xlim`. 

On a more general note, always provide the full error trace when reporting a problem. "Everything breaks." is not terribly specific. ;-)

**Comment by HolgerGH** [comment]
Oops. Well I had this correct before :P .

> #Attempts to enlarge the editing area:
> #ax.set_xlim(auto=True)
> ax.set_xlim(-500,500)
> ax.set_ylim(-200,200)

Using those lines, the plot starts off like this:
![image](https://user-images.githubusercontent.com/45972767/63091718-94c13880-bf5f-11e9-8e3f-b3886b586a6a.png)

It would be ok for me to zoom in at start. But that leads to:
![image](https://user-images.githubusercontent.com/45972767/63091758-b6babb00-bf5f-11e9-8707-cc7f3fdb25ec.png)

So I'm confused, that the aspect ratio gets changed as well. I'm sure this has something to do with me not knowing matplotlib and/or the updating/automatic scaling that is done for the image.

I'm going to learn matplotlib from scratch so I'm sure I will soon understand what happens here.

**Comment by HolgerGH** [comment]
So it still works fine technically. It all breaks just means that you have obviously optimized the layout of the image. And I wondered if there is a way to optimize it for editing. Because you can't drag the nodes out of the axis limits.

**Comment by paulbrodersen** [comment]
I think the easiest would probably be to get the current limits and then increase them by x percent.
For example, 

```python 
xmin, xmax = ax.get_xlim()
xrange = xmax - xmin
xmin -= 0.1 * xrange
xmax += 0.1 * xrange
ax.set_xlim(xmin, xmax)
```

Repeat for the y-limits.
