### ISSUE TITLE
Arrow style unintentinally changed when using Matplotlib 2?

### ISSUE THREAD

**Issue by AllanLRH** [paulbrodersen/netgraph#2]
Hi, first of all, I'm really glad you made this... it produces really nice plots for weighted graphs, which is something I've missing!

There are however some small problems when using Matplotlib 2:
1. There's a gigantic margin around the plot.
2. The arrows are now of the 'fancy' type, not the 'simple' type – see what I mean by 'fancy' and 'simple' in this [Matplotlib Gallery Example](http://matplotlib.org/examples/pylab_examples/fancyarrow_demo.html):

**Your plot:**
![](https://raw.githubusercontent.com/paulbrodersen/netgraph/f677026fda523db2f3dbe503feeda8d93e020c84/example_1.png?raw=true)

**My plot (1200 dpi, white border cropped):**
![](https://raw.githubusercontent.com/AllanLRH/netgraph/c046ddfc6508aac820cb67f2252124aaac59f9f3/example_1_hires_cropped.png?raw=true)

**My plot (Matplotlib default dpi, uncropped):**
![](https://raw.githubusercontent.com/AllanLRH/netgraph/c046ddfc6508aac820cb67f2252124aaac59f9f3/example_1.png?raw=true)

Also, these warnings are thrown:
```
/Users/allan/src/netgraph/netgraph.py:129: RuntimeWarning: invalid value encountered in less
  weights[weights<edge_vmin] = edge_vmin
/Users/allan/src/netgraph/netgraph.py:130: RuntimeWarning: invalid value encountered in greater
  weights[weights>edge_vmax] = edge_vmax
/Users/allan/homeInstalled/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/colors.py:494: RuntimeWarning: invalid value encountered in less
  cbook._putmask(xa, xa < 0.0, -1)
/Users/allan/src/netgraph/netgraph.py:612: RuntimeWarning: invalid value encountered in true_divide
  v = v / np.linalg.norm(v) # unit
/Users/allan/src/netgraph/netgraph.py:620: RuntimeWarning: divide by zero encountered in double_scalars
  dx *= (r-offset)/r
/Users/allan/src/netgraph/netgraph.py:620: RuntimeWarning: invalid value encountered in double_scalars
  dx *= (r-offset)/r
/Users/allan/src/netgraph/netgraph.py:621: RuntimeWarning: divide by zero encountered in double_scalars
  dy *= (r-offset)/r
/Users/allan/src/netgraph/netgraph.py:621: RuntimeWarning: invalid value encountered in double_scalars
  dy *= (r-offset)/r
```

**Comment by paulbrodersen** [comment]
Yeah, I just migrated to matplotlib 2.0 and also noticed the gigantic margins and the weird new arrow behaviour. I tried to fix the margins for a couple of minutes the other but couldn't find an quick solution (and had to move on as I have deadline coming up). If you find a solution, let me know. Otherwise, I will give it another stab on the weekend. The culprit should be within `update_view`, I think. 

The new arrow behaviour is a known matplotlib "bug" (see e.g. http://stackoverflow.com/questions/43586086/matplotlib-patches-fancyarrow-has-thinned-out-tail/43588158). Should not be too hard to fix -- I will give it a stab later today.

**Comment by paulbrodersen** [comment]
Mhm, the tapering that FancyArrow in matplotlib 2.0.0 displays is a clear matplotlib bug. 
Essentially, for shape="full" coords in 2.0.0 are

```python
coords = np.concatenate([left_half_arrow[:-1], right_half_arrow[-2::-1]])
```

when they should be:

```python
coords = np.concatenate([left_half_arrow[:-1], right_half_arrow[-1::-1]])
```

I have included a fixed version of FancyArrow with the code until matplotlib get their act together.

**Comment by paulbrodersen** [comment]
I fixed `_update_view()` and margins should work now as intended as well (this time my code was to blame, not matplotlib). If that fixes the problem for you, too, I will close the issue.

**Comment by AllanLRH** [comment]
Nice, it also works on my machine 👍
