### ISSUE TITLE
zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by ErikHartman** [paulbrodersen/netgraph#25]
Trying to create a community network graph but fails with the error:
`*ValueError: zero-size array to reduction operation minimum which has no identity*`

Everything works using networksx, but since netgraph allows for edge bundling and prettier graphs I would love for it to work.
The only code needed to reproduce would be the one below (*links_filtered* is a pandas edgelist).

`G=nx.from_pandas_edgelist(links_filtered, 'from', 'to')`

`node_to_community = community.community_louvain.best_partition(G)`

`Graph(G, node_layout='community', node_layout_kwargs=dict(node_to_community=node_to_community))`

**Comment by paulbrodersen** [comment]
Sorry, but that is not enough information to debug the issue. Can you add

1) the full error trace,
2) the edges in `links_filtered`, and
3) the `node_to_community` 

to your post? Then I will have a look. If the network is very large, it might be best to export the edge list and community partition to csv spreadsheets.

**Comment by ErikHartman** [comment]
Thank you for your quick response! In the attached "troubleshooting.zip" folder you'll find .csv of links_filtered and node_to_communityHere is the full error trace:

`RuntimeWarning: divide by zero encountered in double_scalars
  k = np.sqrt(area / float(total_nodes))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-c22598055559> in <module>
     10 node_to_community = community.community_louvain.best_partition(G)
     11 
---> 12 Graph(G,node_edge_width=0, edge_alpha=0.1, node_layout='community', node_layout_kwargs=dict(node_to_community=node_to_community))

~\OneDrive\Dokument\GitHub\igseq\.venv\lib\site-packages\netgraph\_main.py in __init__(self, graph, edge_cmap, *args, **kwargs)
   2111             kwargs.setdefault('node_zorder', node_zorder)
   2112 
-> 2113         super().__init__(edges, *args, **kwargs)
   2114 
   2115 

~\OneDrive\Dokument\GitHub\igseq\.venv\lib\site-packages\netgraph\_main.py in __init__(self, edges, nodes, node_layout, node_layout_kwargs, node_shape, node_size, node_edge_width, node_color, node_edge_color, node_alpha, node_zorder, node_labels, node_label_offset, node_label_fontdict, edge_width, edge_color, edge_alpha, edge_zorder, arrows, edge_layout, edge_layout_kwargs, edge_labels, edge_label_position, edge_label_rotate, edge_label_fontdict, origin, scale, prettify, ax, *args, **kwargs)
   1066 
   1067         # Initialise node and edge layouts.
-> 1068         self.node_positions = self._initialize_node_layout(
   1069             node_layout, node_layout_kwargs, origin, scale, node_size)
   1070 

~\OneDrive\Dokument\GitHub\igseq\.venv\lib\site-packages\netgraph\_main.py in _initialize_node_layout(self, node_layout, node_layout_kwargs, origin, scale, node_size)
   1206             if (node_layout == 'spring') or (node_layout == 'dot'):
   1207                 node_layout_kwargs.setdefault('node_size', node_size)
-> 1208             return self._get_node_positions(node_layout, node_layout_kwargs, origin, scale)
   1209 
   1210         elif isinstance(node_layout, dict):

~\OneDrive\Dokument\GitHub\igseq\.venv\lib\site-packages\netgraph\_main.py in _get_node_positions(self, node_layout, node_layout_kwargs, origin, scale)
   1221             return node_positions
   1222         if node_layout == 'community':
-> 1223             node_positions = get_community_layout(
   1224                 self.edges, origin=origin, scale=scale, **node_layout_kwargs)
   1225             if len(node_positions) > 3: # Qhull fails for 2 or less nodes

~\OneDrive\Dokument\GitHub\igseq\.venv\lib\site-packages\netgraph\_node_layout.py in wrapped_layout_function(edges, nodes, *args, **kwargs)
     57 
     58         if len(components) > 1:
---> 59             return get_layout_for_multiple_components(edges, components, layout_function, *args, **kwargs)
     60         else:
     61             return layout_function(edges, *args, **kwargs)

~\OneDrive\Dokument\GitHub\igseq\.venv\lib\site-packages\netgraph\_node_layout.py in get_layout_for_multiple_components(edges, components, layout_function, origin, scale, *args, **kwargs)
    152         if len(component) > 1:
    153             subgraph = _get_subgraph(edges, component)
--> 154             component_node_positions = layout_function(subgraph, origin=bbox[:2], scale=bbox[2:], *args, **kwargs)
    155             node_positions.update(component_node_positions)
    156         else:

~\OneDrive\Dokument\GitHub\igseq\.venv\lib\site-packages\netgraph\_node_layout.py in get_community_layout(edges, node_to_community, origin, scale)
    864 
    865     community_size = _get_community_sizes(node_to_community, scale)
--> 866     community_centroids = _get_community_positions(edges, node_to_community, community_size, origin, scale)
    867     relative_node_positions = _get_node_positions(edges, node_to_community)
    868 

~\OneDrive\Dokument\GitHub\igseq\.venv\lib\site-packages\netgraph\_node_layout.py in _get_community_positions(edges, node_to_community, community_size, origin, scale)
    893 
    894     # find layout for communities
--> 895     return get_fruchterman_reingold_layout(
    896         list(between_community_edges.keys()), edge_weight=between_community_edges,
    897         node_size=community_size, origin=origin, scale=scale,

~\OneDrive\Dokument\GitHub\igseq\.venv\lib\site-packages\netgraph\_node_layout.py in wrapped_layout_function(edges, nodes, *args, **kwargs)
     59             return get_layout_for_multiple_components(edges, components, layout_function, *args, **kwargs)
     60         else:
---> 61             return layout_function(edges, *args, **kwargs)
     62 
     63     return wrapped_layout_function

~\OneDrive\Dokument\GitHub\igseq\.venv\lib\site-packages\netgraph\_node_layout.py in get_fruchterman_reingold_layout(edges, edge_weights, k, scale, origin, initial_temperature, total_iterations, node_size, node_positions, fixed_nodes, *args, **kwargs)
    447 
    448     if np.all(is_mobile):
--> 449         node_positions_as_array = _rescale_to_frame(node_positions_as_array, origin, scale)
    450 
    451     node_positions = dict(zip(unique_nodes, node_positions_as_array))

~\OneDrive\Dokument\GitHub\igseq\.venv\lib\site-packages\netgraph\_node_layout.py in _rescale_to_frame(node_positions, origin, scale)
    540 def _rescale_to_frame(node_positions, origin, scale):
    541     node_positions = node_positions.copy() # force copy, as otherwise the `fixed_nodes` argument is effectively ignored
--> 542     node_positions -= np.min(node_positions, axis=0)
    543     node_positions /= np.max(node_positions, axis=0)
    544     node_positions *= scale[None, ...]

<__array_function__ internals> in amin(*args, **kwargs)

~\OneDrive\Dokument\GitHub\igseq\.venv\lib\site-packages\numpy\core\fromnumeric.py in amin(a, axis, out, keepdims, initial, where)
   2856     6
   2857     """
-> 2858     return _wrapreduction(a, np.minimum, 'min', axis, None, out,
   2859                           keepdims=keepdims, initial=initial, where=where)
   2860 

~\OneDrive\Dokument\GitHub\igseq\.venv\lib\site-packages\numpy\core\fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     85                 return reduction(axis=axis, out=out, **passkwargs)
     86 
---> 87     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     88 
     89 

ValueError: zero-size array to reduction operation minimum which has no identity`


[troubleshooting.zip](https://github.com/paulbrodersen/netgraph/files/6753438/troubleshooting.zip)

**Comment by paulbrodersen** [comment]
Hi, thanks for raising the issue. The layout function fails as there are a number of problems with your data. However, the issue did highlight a few places in my code that needed a bit more defensive programming for which I am grateful.  

The main problems with your data are:

1) Your data is incomplete. For example, there are several nodes that do not have an entry in the node_to_community file you sent me (for example node 927). 

2) Your graph consists of a lot of disconnected components.

```python
import numpy as np
import pandas as pd
import networkx as nx

df_edges = pd.read_csv('~/Downloads/troubleshooting/links_filtered.csv', usecols=['from', 'to'])
edges = df_edges.values.tolist()
components = nx.components.connected_components(nx.Graph(edges))
component_sizes = [len(component) for component in components]
print(np.bincount(component_sizes))
# [ 0  0 38 16  2  1  2  4  1  4  0  2  2  3  3  2  2  0  0  2  2  0  1  1
#   0  2  2  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  1]
```

`netgraph` is smart enough to deal with disconnected components and processes each component individually. However, as you can see in the code snippet above, most of the components consist of a single edge. However, a graph that consists of a single edge cannot be modular in any reasonable sense, and hence the Louvain algorithm assigns a single community to all nodes in those components. The community layout then fails as it expects a modular graph, i.e. a graph with more than a single community.

I have made some changes to netgraph so that the `community_layout` does not fail in these cases but simply computes a different layout instead. If you fix you data (see point 1) and then download the latest version from github, the function runs and produces the following graph:

![Figure_1](https://user-images.githubusercontent.com/8046146/124282858-309fc180-db43-11eb-96a5-03d6eec5d917.png)

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from netgraph import Graph

df_edges = pd.read_csv('~/Downloads/troubleshooting/links_filtered.csv', usecols=['from', 'to'])
edges = df_edges.values.tolist()

df_partition = pd.read_csv('/home/paul/Downloads/troubleshooting/node_to_community.csv', usecols=[1,2])
df_partition.rename(columns={'0' : 'node', '1' : 'community'}, inplace=True)
partition = dict(df_partition.values.tolist())

# remove edges that contain nodes without a community assigned to them
cleaned = [(source, target) for source, target in edges if (source in partition) and (target in partition)]

# get some colors
communities = np.unique(list(partition.values()))
indices = np.random.choice(len(mcolors.CSS4_COLORS), replace=False, size=len(communities))
colors = list(mcolors.CSS4_COLORS.keys())
community_to_color = dict()
for community, idx in zip(communities, indices):
    community_to_color[community] = colors[idx]
node_color = {node: community_to_color[community_id] for node, community_id in partition.items()}

Graph(cleaned, node_size=1, edge_width=0.1,
      node_color=node_color, node_edge_width=0, edge_alpha=0.1,
      node_layout='community', node_layout_kwargs=dict(node_to_community=partition),
      edge_layout='bundled')

plt.show()
```

However, as you can see, none of the components is actually modular, i.e. has a community structure.

**Comment by ErikHartman** [comment]
It's working now!

Being a student, I'm very thankful for people like you who respond quickly and provide simple explanations. The lack of community structure will be dealt with by tweakings in the pre-processing.

Thank you so much and have a great weekend.

**Comment by paulbrodersen** [comment]
Glad I could help, and have a good week!
