### ISSUE TITLE
pip install doesn't install networkx

### ISSUE THREAD

**Issue by jacobwilliams** [paulbrodersen/netgraph#31]
Should the `setup.py` include `networkx` as a dependency?

**Comment by paulbrodersen** [comment]
It shouldn't. Do you have problems importing the module without networkx installed?

**Comment by jacobwilliams** [comment]
Ah, I was running one of the examples in the readme, and now I see that's where the `networkx` import is coming from. Never mind!

**Comment by jacobwilliams** [comment]
Very cool library btw!!

**Comment by paulbrodersen** [comment]
Ah, I see what you mean. The very first example in the readme indeed uses a networkx graph as one of the example inputs but networkx isn't explicitly imported at the start of the script. I will think about how to handle that better. Thanks for raising the issue and glad you like it!
