### ISSUE TITLE
help with drawing a flowchart

### ISSUE THREAD

**Issue by s0ap** [paulbrodersen/netgraph#32]
I have two models both of which can output a value from fixed set of values (say ["A", "B", "C"]). For example, model_1 = ["A", "B", "C"], model_1 = ["A", "B", "C"]

I want to create a flowchart with starting nodes as model_1 and model_2 to show the following logic -
```
if output_model_1 = "A" and output_model_2 = "A":
   final_output = "A"
elif output_model_1 = "B" and output_model_2 = "B":
  final_output = "B"
elif output_model_1 = "C" and output_model_2 = "C":
  final_output = "C"
elif (output_model_1 = "A" and output_model_2 = "B") or (output_model_1 = "B" and output_model_2 = "A"):
  final_output = "C"
elif (output_model_1 = "A" and output_model_2 = "C") or (output_model_1 = "C" and output_model_2 = "A"):
  final_output = "A"
elif (output_model_1 = "B" and output_model_2 = "C") or (output_model_1 = "C" and output_model_2 = "B"):
  final_output = "B"
```

Can you please help? Many thanks!

**Comment by paulbrodersen** [comment]
Can you make a sketch with pen and paper? I don't really understand what you want to show.

**Comment by paulbrodersen** [comment]
Closing the issue due to inactivity. Feel free to re-open.
