### ISSUE TITLE
How to modify node_label_fontdict?

### ISSUE THREAD

**Issue by fishbacp** [paulbrodersen/netgraph#36]
I apologize for posting this here, as it is not a bug or issue but instead a question regarding the adjustment of node label font sizes, one that I doubt would yield a response on StackOverflow. 

At https://netgraph.readthedocs.io/en/latest/graph_classes.html

it states that ```node_label_fontdict```  consists of keyword arguments passed to matplotlib.text.Text. I'm looking at matplotlib.text.Text right now and see the familiar keyword argument ```fontsize```.  It's not clear what an example dictionary, ```node_label_fontdict``` would look like if I merely wanted to change my label font size. 

BTW, this package is really nice. I plan to use it for community detection in the context of EEG signal analysis.

**Comment by paulbrodersen** [comment]
> I apologize for posting this here, as it is not a bug or issue but instead a question regarding the adjustment of node label font sizes, one that I doubt would yield a response on StackOverflow.

That's totally fine. The fact that even after reading the documentation you are unsure what to do means that the documentation needs more work. 

Basically, `node_label_fontdict` is dictionary with key-value pairs that are passed to `matplotlib.text.Text`. 
The following command sets the fontsize to 20 pts:

```python
Graph(nx.complete_graph(7), node_labels=True, node_label_fontdict=dict(size=20))
```

There are a few more examples [here](https://netgraph.readthedocs.io/en/latest/sphinx_gallery_output/plot_06_labels.html#sphx-glr-sphinx-gallery-output-plot-06-labels-py).

**Comment by paulbrodersen** [comment]
Also, thanks to your post I just learnt that `fontsize` is now a valid keyword for matplotlib `Text` objects. It used to be just `size`, now both is supported in matplotlib. However, looking at my code, I can see at least one set of circumstances in which a font size specification via `fontsize` would not be correctly handled. So apologies if you tried using that keyword instead of `size` and you got an error. That is a proper bug.

**Comment by fishbacp** [comment]
Thanks so much. This is great!
