### ISSUE TITLE
Deprecation issue installing netgraph

### ISSUE THREAD

**Issue by fsoupimenta** [paulbrodersen/netgraph#54]
I tried to install netgraph in my project, and this problem appeared;
```shell
DEPRECATION: netgraph is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```

Would it be possible to update netgraph to match these new installation settings?

**Comment by paulbrodersen** [comment]
This is just a deprecation warning, i.e. the package still installs fine, correct? 

I have a hard deadline next week, so assuming this is a non-breaking issue, then I will look into it afterwards.

**Comment by fsoupimenta** [comment]
You are right! It was just a warning to alert you, nothing breaks.

**Comment by paulbrodersen** [comment]
Hi @fsoupimenta, thanks for bringing the issue to my attention. I have switched from a `setup.py` based installation to a `pyproject.toml`/ `wheel` based installation. As a result, `pip` should no longer raise a deprecation warning.
