### ISSUE TITLE
Hyperlink or selectable text from annotations?

### ISSUE THREAD

**Issue by a-arbabian** [paulbrodersen/netgraph#56]
Hey,

I'm currently using the library on a project and have a usecase for linking to a URL based on node attributes. I have the annotation showing on node click, but realized that the link is not selectable or clickable. Would it be possible to do either of those (hyperlinks would be preferred but selectable text is good too)?

Thanks

**Comment by paulbrodersen** [comment]
Hi, thanks for raising the issue, that is an interesting use case. 

As you may know, netgraph uses matplotlib for drawing all visual elements, including text objects. However, matplotlib doesn't really do hyperlinks, as the imagined end-point is an image (and images are not text files, and hence don't support hyperlinks). Matplotlib does support hyperlinks when using the SVG backend (as SVG files are text files, ultimately) but the SVG backend is not interactive. As netgraph makes ample use of matplotlib's interactive events, netgraph cannot support matplotlib hyperlinks. 

**However**,  it is fairly straightforward to emulate hyperlinks using matplotlib pick events in combination with the (python built-in) `webbrowser` module. Below some examples.

```python
#!/usr/bin/env python
import webbrowser
import matplotlib.pyplot as plt

from netgraph import InteractiveGraph

fig, ax = plt.subplots()

# Enable picking.
def on_pick(event):
    if isinstance(event.artist, plt.Text):
        webbrowser.open(event.artist.get_text())

fig.canvas.mpl_connect('pick_event', on_pick)

# Define some links.
node_labels = {
    0 : "https://stackoverflow.com/a/54121221/2912349",
    1 : "https://stackoverflow.com/a/69682368/2912349"
}

annotations = {(0, 1) : "https://matplotlib.org/stable/gallery/event_handling/pick_event_demo.html"}

# Create a graph.
g = InteractiveGraph([(0, 1)], node_labels=node_labels, node_label_offset=0.05, annotations=annotations, ax=ax)

# Enable pick events on text objects.
# By (matplotlib) default, pick events are disabled.
for text_object in g.node_label_artists.values():
    text_object.set_picker(True)

# Annotation text objects are created on-the-fly.
# We hence have to monkkeypatch the InteractiveGraph instance to enable the picker,
# whenever an annotation is created.

original_add_annotation = g._add_annotation

def new_add_annotation(artist, *args, **kwargs):
    original_add_annotation(artist, *args, **kwargs)
    text_object = g.artist_to_text_object[artist]
    text_object.set_picker(True)

g._add_annotation = new_add_annotation

plt.show()

################################################################################
# Naturally, hyperlinks need not be text objects.

from netgraph._artists import NodeArtist, EdgeArtist

fig, ax = plt.subplots()

def on_pick(event):
    if isinstance(event.artist, (NodeArtist, EdgeArtist)):
        if hasattr(event.artist, 'url'):
            webbrowser.open(event.artist.url)

fig.canvas.mpl_connect('pick_event', on_pick)

g = InteractiveGraph([(0, 1)], node_labels=True, ax=ax)

g.node_artists[0].set_picker(True)
g.node_artists[0].url = "www.google.com"

g.edge_artists[(0, 1)].set_picker(10) # increase pick radius for thin edges
g.edge_artists[(0, 1)].url = "www.stackoverflow.com"

plt.show()
```

I hope that addresses your issue. Make sure to install the latest version as I just fixed a bug that occurred when annotating edges (or change the edge annotation to a node annotation in the example above).

**Comment by paulbrodersen** [comment]
I have added some simple examples to the documentation [here](https://netgraph.readthedocs.io/en/latest/sphinx_gallery_output/plot_19_hyperlinks.html#sphx-glr-sphinx-gallery-output-plot-19-hyperlinks-py). I will close the issue for now, but feel free to re-open it if you have any further concerns.

**Comment by a-arbabian** [comment]
Wow thanks for the excellent write up! Will try this next week 👍

**Comment by paulbrodersen** [comment]
You probably forgot to enable the picker?

```python
import webbrowser
import matplotlib.pyplot as plt

from netgraph import InteractiveGraph

def on_pick(event):
    webbrowser.open(event.artist.get_url())

fig, ax = plt.subplots()
g = InteractiveGraph([(0, 1)], node_labels=True, annotations={0 : dict(s='lorem ipsum', url='www.google.com', picker=True)})
fig.canvas.mpl_connect('pick_event', on_pick)
plt.show()
```

**Comment by a-arbabian** [comment]
Seemed to be an issue with `webbrowser` module, got it working now thanks!
