### ISSUE TITLE
is a conda package available somewhere?

### ISSUE THREAD

**Issue by rjalexa** [paulbrodersen/netgraph#57]
Dear Dr. Brodersen,
I manage my python environments using conda, not pip.

Is there a way to install your beautiful library with it?

Not sure how to flag this as just as a nice to have, not a bug.

**Comment by paulbrodersen** [comment]
Hi Robert

netgraph isn't currently uploaded to conda-forge. For a package to be eligible for conda-forge, all of its dependencies have to be on conda-forge. It used to be the case that several dependencies were not on conda, so I didn't even consider it. However, it seems that now the only dependency missing is `retangle-packer`, and they have a conda package on their own channel. As it is not a huge jump from there to publishing it on conda-forge, I will raise an issue with them and see if they have plans / can be persuaded to publish their package there. 

In the meantime, you can install netgraph [using pip inside an anaconda environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#installing-non-conda-packages), as anaconda maintains compatibility with pip and by default comes with pip pre-installed in each environment.  

Best,
Paul

**Comment by paulbrodersen** [comment]
Mhm, actually, it looks like somebody other than the author uploaded rectangle-packer to anaconda.

**Comment by rjalexa** [comment]
Thanks a lot Paul. Yes as of now I did install via pip even though when you generate requirements down the line mixed environments often spell trouble. I see you are a computational neuroscientist, how interesting. I am a medical practitioner dabbling with AI (mostly NLP and knowledge graphs)! Take care and have a great winter holiday.

**Comment by paulbrodersen** [comment]
If you don't mind, I would like to leave the issue open. It's worth doing and I will otherwise forget to chase the author of rectangle-packer. ;-)

**Comment by paulbrodersen** [comment]
netgraph and all of its dependencies are now available via conda-forge:

```shell
conda install -c conda-forge netgraph
```

**Comment by rjalexa** [comment]
Thank you very much on behalf of all conda/mamba users :) Take care
