### ISSUE TITLE
Netgraph InteractiveGraph not interactive on Google Colab ?

### ISSUE THREAD

**Issue by rjalexa** [paulbrodersen/netgraph#59]
Very simple example of an InteractiveGraph showing all of a node's attributes in a table (what an awesome super duper feature thanks)

https://colab.research.google.com/drive/1X6KmadaUm92EEHkUbIKg3ysSYov_ohVy

Works fine in local (both jupyter notebook or script), not sure why it just draws the initial static graph and that's all folks)

Happy Xmas !!!

**Comment by paulbrodersen** [comment]
Google colab [doesn't support interactive matplotlib figures](https://github.com/googlecolab/colabtools/issues/616). Happy Christmas to you, too!
