### ISSUE TITLE
Collapse and expand descendents of node on click

### ISSUE THREAD

**Issue by a-arbabian** [paulbrodersen/netgraph#60]
Hey again,
I have another use case that I did not see in the examples. For a tree (networkx.DiGraph to be specific), I want to be able to collapse/expand a node's descendents on click. 
I can work on this implementation sometime this week, but just wanted to see if you forsee any matplotlib or `InteractiveGraph` limitations that would prevent this feature. Or maybe there is already code for this that I missed.

Thanks!

**Comment by paulbrodersen** [comment]
I have thought about building that but it really only works for graphs that are trees so I dropped the idea, as at the time, I only wanted to add features that are more generally applicable. I did implement a class were you could merge/unmerge (?) nodes to construct hypergraphs on the fly. However, nobody ever seemed to use that feature so I eventually removed it again as it made a number of other things very complicated. The code is extremely unlikely to work with present versions of netgraph but the commit is [here](https://github.com/paulbrodersen/netgraph/commit/98d39938d385bc9ea77d8c4493058f6e06341876) if you are interested.
