### ISSUE TITLE
Support for `EditableGraph` with no edges

### ISSUE THREAD

**Issue by fsoupimenta** [paulbrodersen/netgraph#62]
Hello, 
I'm working on a [project](https://github.com/GraphFilter/GraphFilter/issues/240) that uses Netgraph, and when i tried to plot a graph without an edge, i got the following traceback:

```
assert len(edges) > 0, "The list of edges has to be non-empty."
AssertionError: The list of edges has to be non-empty
```
There is a way to plot a graph with no edges? Or implement it?

**Comment by hdahmou** [comment]
Hi,

Would you mind sharing a simple code example that replicates the issue you are experiencing? I have not been able to reproduce the issue on my end:

```
  import networkx as nx
  import netgraph
  
  g = nx.Graph()
  g.add_nodes_from([0, 1, 2, 3])
  
  I = netgraph.Graph(g)
```
![output](https://user-images.githubusercontent.com/120108478/225873505-9e2a3713-f915-433c-bfc9-4c41e735b657.png)

Thanks

**Comment by paulbrodersen** [comment]
Note that empty graphs, i.e. graphs without nodes, are still out of scope. You would have to catch these occurrences in your own code base, presumably right before you hand the graph data object to netgraph.

**Comment by paulbrodersen** [comment]
`EditableGraph` uses the existing node and edge artists to style any new ones that are created on-the-fly via hotkeys. If there are no edges, then you run into the error above. I hadn't considered this issue when I implemented support for graphs with no edges. I will look into it next week.

**Comment by paulbrodersen** [comment]
Version 4.12.5 supports empty graphs in the `EditableGraph` class. It uses the parameters provided during instantiation to style the nodes and edges. 

```python
import matplotlib.pyplot as plt

from netgraph import EditableGraph

g = []

# import networkx as nx
# g = nx.Graph()

# import igraph
# g = igraph.Graph()

# import graph_tool
# g = graph_tool.Graph()

h = EditableGraph(g, node_color='red', node_edge_color='red', edge_color='orange')
plt.show()
```

**Comment by paulbrodersen** [comment]
I forgot about the case, where the graph contains nodes but no edges. Hold on...

**Comment by paulbrodersen** [comment]
Feel free to re-open if you encounter any more bugs.

**Comment by fsoupimenta** [comment]
I already tested it and it worked fine, thank you!
