### ISSUE TITLE
Installation not working with python 3.11

### ISSUE THREAD

**Issue by ortega2247** [paulbrodersen/netgraph#68]
I tried installing netgraph using conda and python 3.11 in a windows machine and got the following error:

`ImportError: DLL load failed while importing _imaging: The specified module could not be found.
`

**Comment by paulbrodersen** [comment]
Thanks for raising the issue. Unfortunately, I can't be of help in this case. Netgraph does not contain an `_imaging` module.

A quick google search suggests that `PIL` / `pillow` may be the culprit; to be sure, however, you would have know the complete error trace. If that is indeed the case, I would suggest installing `pillow` separately, or upgrading `pillow` if you have an existing installation. `pillow` is a dependency of matplotlib (IIRC) but netgraph does not use any of the related features so any `pillow` version should work (even none at all) as far as netgraph is concerned.

As I am not author/maintainer of the `_imaging` module, and can't provide further assistance, I will close the issue for now.

**Comment by rkurchin** [comment]
Linking to [JOSS review](https://github.com/openjournals/joss-reviews/issues/5372) and popping in to note: I think if there are installation hiccups on the latest version of Python, we should make sure any gotchas are documented – @ortega2247, can you confirm whether the stacktrace does implicate `pillow` and whether installing NetGraph in a clean conda environment (i.e. without preexisting `pillow` and/or `matplotlib` installations) still causes this issue?

**Comment by paulbrodersen** [comment]
> I think if there are installation hiccups on the latest version of Python, we should make sure any gotchas are documented

I am sorry but I can't monitor all upstream packages for installation issues on all platforms. I have neither the time nor resources to do so. The `pillow` team is very active. If indeed there is an issue with `pillow` on some windows platforms, I have no way of knowing if and when it is resolved. On my windows installation, `pillow` installs without errors when using conda.

**Comment by rkurchin** [comment]
Understood. Another thing you could consider would be setting up CI – there are standard Windows runners (and other OSes as well obviously), which would at least let you catch if the "standard" environment/setup trips up, either due to changes in commits you introduce or to upstream packages.

**Comment by paulbrodersen** [comment]
@rkurchin Absolutely. Setting up CI is already on my TODO list but I haven't got around to it yet. As there are two major tickets that I would like to address first (major release with support for multigraphs, improved integration tests), it won't happen in time for this review.
