### ISSUE TITLE
netgraph doesn't recognize nx.DiGraph() as a directed graph

### ISSUE THREAD

**Issue by kkdd** [paulbrodersen/netgraph#7]
Hello,
When running the following code, netgraph doesn't draw arrows on edges.
Doesn't netgraph recognize the following G as a directed graph?

```python
import matplotlib.pyplot as plt
import netgraph
import networkx as nx
n = 5
G = nx.DiGraph()
G.add_nodes_from(range(n))
G.add_edges_from([(i, (i+1)%n) for i in range(n)]) # directed cycle
plt.subplots(1,1)
netgraph.draw(G, directed=True) # doesn't draw arrows
plt.show()
```

![cycle_graph](https://user-images.githubusercontent.com/5372642/35216092-c154ae80-ffa9-11e7-94de-f4a8b01e281a.png)

**Comment by paulbrodersen** [comment]
There is no `directed` keyword argument for `draw`. What you are looking for is `draw_arrows`. 

```python
import matplotlib.pyplot as plt
import netgraph
import networkx as nx
n = 5
G = nx.DiGraph()
G.add_nodes_from(range(n))
G.add_edges_from([(i, (i+1)%n) for i in range(n)]) # directed cycle
plt.subplots(1,1)
# netgraph.draw(G, directed=True) # doesn't draw arrows
netgraph.draw(G, draw_arrows=True)
plt.show()
```

![figure_1-1](https://user-images.githubusercontent.com/8046146/35219428-846f052c-ff6a-11e7-8847-e3c50aa92a36.png)

I do agree with the sentiment though, that `draw` should recognize a `DiGraph` as directed and plot the arrows by default. I will look into it some time this week, probably on the weekend.

**Comment by paulbrodersen** [comment]
Postponed lunch break, and fixed my code. The newest version on github should draw directed `networkx` graph objects with arrows by default (ditto for `igraph`). I haven't updated the version on PyPI, yet, as I don't have time now to test the new version as much as I would like.

**Comment by kkdd** [comment]
Thank you.
![nxgraph](https://user-images.githubusercontent.com/5372642/35223021-54b1e4ae-ffc3-11e7-8d3e-0c04a9e37153.jpg)

```python
import matplotlib.pyplot as plt
import netgraph
import networkx as nx
n = 5
G = nx.DiGraph()
G.add_nodes_from(range(n))
G.add_edges_from([(i, (i+1)%n) for i in range(n)])
G.add_edges_from([(1,0)])
plt.subplots(1,1)
netgraph.draw(G, draw_arrows=True, node_size=7, node_labels=dict([(n,n) for n in G.nodes()]))
plt.show()
```

**Comment by paulbrodersen** [comment]
No, thank you for the bug report (keep them coming!). I also just pushed a new version to PyPI, so the pip installable version should implement this behavior now, too.
