### ISSUE TITLE
Unable to use Community layout for Multi-Component graph?

### ISSUE THREAD

**Issue by a-arbabian** [paulbrodersen/netgraph#75]
Hello,

I have a multi component graph where connections between nodes, even within the same community, are not guaranteed. I have color coded the nodes based on community, but cannot get the community layout to run with my graph, getting the following error:
```
netgraph/_node_layout.py:1549: UserWarning: Graph contains a single community. Unable to compute a community layout. Computing spring layout instead.
```
After some quick debugging I saw that `get_community_layout()` infers the nodes from the edges. I also saw some past issues about the community layout needing edges within communities (and also between communities if I'm not mistaken?).
I tried a workaround where I added invisible edges between nodes within the same community, but that did not solve the error.

Maybe my use-case is not meant for the community layout, but I'm basically trying to visually cluster the nodes which are in the same community (and thus same color) regardless of connectivity within the communities. For example, even if a community has two clusters between which there are no edges, I want the two clusters to plot next to each other.

I am using version 4.12.11 and plotting a `networkx.DiGraph` for reference.

**Comment by paulbrodersen** [comment]
That is just a warning, not an error. Presumably, you have some unconnected nodes in your example, and for those nodes (and those nodes only), the position is not determined using the community layout but the spring layout. Does the visualisation look correct?

**Comment by a-arbabian** [comment]
I see, I didn't realize the warning was per node, not for the entire layout. 
The visualization is fine except for multi-component communities. As you can see from the image, if one or more nodes are disconnected from the rest of the community, they are not plotted together. 

I can think of a workaround where I check for disconnected nodes within a community, and add invisible edges to them. 
Do you think it's worth covering this use-case and/or the implementation would be doable? I'm not super familiar with the algorithm for the community layout so I can't tell.

<img width="972" alt="Screenshot 2023-08-08 at 1 14 00 PM" src="https://github.com/paulbrodersen/netgraph/assets/45885885/864b84ba-f0e4-43e0-b846-3d81664a3d03">

**Comment by paulbrodersen** [comment]
Closing the issue for now but feel free to re-open if you have further questions w.r.t. this issue or my suggestions.
